spring:

  datasource:
    url: jdbc:postgresql://postgres-db-new/postgres
    username: postgres
    password: 0095
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
